CREATE SEQUENCE SEQ_MATCHING_POST; -- 매칭글SEQ
CREATE SEQUENCE SEQ_MATCHING_POST_LIKE; -- 매칭글좋아요SEQ 
CREATE SEQUENCE SEQ_CHATROOM_NO; -- 채팅방번호(채팅)

DROP SEQUENCE SEQ_MATCHING_POST;
DROP SEQUENCE SEQ_MATCHING_POST_LIKE;
DROP SEQUENCE SEQ_CHATROOM_NO;


 CREATE TABLE CHAT (  ---------------------------------------------------------- 채팅
    CHATROOM_NO NUMBER,                           -- 채팅방 번호   
    CHAT_START DATE DEFAULT SYSDATE,           -- 대화시작날짜시간
    CHAT_END DATE DEFAULT SYSDATE              -- 대화종료날짜시간
);
SELECT * FROM CHAT;
DROP TABLE CHAT;


CREATE TABLE CHAT_USER_INFO (  ------------------------------------------------- 채팅참여유저정보
    CHATROOM_NO NUMBER,                                        -- 채팅방번호
    CU_ID VARCHAR2(50),                                   -- 채팅발송유저아이디
    CHAT_CONTENT VARCHAR2(300),                                 -- 채팅내용
    CHAT_SENT_TIME TIMESTAMP,                                    -- 발송시각
    READ_STATUS VARCHAR2(1) DEFAULT 'N' CHECK(READ_STATUS IN('Y', 'N'))          -- 읽음표시(Y/N)
);
SELECT * FROM CHAT_USER_INFO;
DROP TABLE CHAT_USER_INFO;

CREATE TABLE MATCHING_POST (    ---------------------------------  매칭글
    MP_SEQ NUMBER,
    MP_TITLE VARCHAR2(100) NOT NULL,             -- 매칭글제목
    MP_CONTENT VARCHAR2(3000) NOT NULL,          -- 매칭글내용
    MP_POST_TIME TIMESTAMP,                      -- 매칭글작성시각
    MP_VIEWS NUMBER,                             -- 매칭글조회수
    MP_URL VARCHAR2(200) NOT NULL,               -- 매칭글주소
    MATCHING_ACCEPT VARCHAR(1) DEFAULT 'N' CHECK(MATCHING_ACCEPT IN('Y', 'N')),                          -- 매칭승락(Y/N)
    NOTICE VARCHAR(1) DEFAULT 'N' CHECK(NOTICE IN('Y', 'N')),    -- 공지사항(Y/N) 
    CATEGORY_SEQ NUMBER,
    MP_AUTHOR VARCHAR2(50)       -- 매칭글 작성자
);
SELECT * FROM MATCHING_POST;
DROP TABLE MATCHING_POST;

CREATE TABLE MATCHING_POST_LIKE (  ------------------------------------ 매칭글좋아요
    MP_LIKE_SEQ NUMBER,
    LIKE_TIME TIMESTAMP,                                      -- 매칭글좋아요누른시간
    MP_SEQ NUMBER,
    MP_LIKE_USER VARCHAR2(50)                     -- 아이디
);
SELECT * FROM MATCHING_POST_LIKE;
DROP TABLE MATCHING_POST_LIKE;

-- PK ----
ALTER TABLE CHAT ADD CONSTRAINT CHATROOM_NO_PK PRIMARY KEY(CHATROOM_NO); -- 채팅(채팅방번호)
ALTER TABLE CHAT_USER_INFO ADD CONSTRAINT CHATROOM_NUMBER_PK PRIMARY KEY(CHATROOM_NO); -- 채팅참여유저정보(채팅방번호)
ALTER TABLE MATCHING_POST ADD CONSTRAINT MATCHING_POST_SEQ_PK PRIMARY KEY(MP_SEQ); -- 매칭글(매칭글SEQ)
ALTER TABLE MATCHING_POST_LIKE ADD CONSTRAINT MATCHING_POST_LIKE_SEQ_PK PRIMARY KEY(MP_LIKE_SEQ); -- 매칭글좋아요(매칭글좋아요SEQ)



-- FK --

ALTER TABLE MATCHING_POST ADD CONSTRAINT MATCHING_POST_FK FOREIGN KEY(CATEGORY_SEQ) REFERENCES CATEGORY;   --  매칭글(카테고리SEQ)
ALTER TABLE MATCHING_POST ADD CONSTRAINT MATCHING_POST_FK2 FOREIGN KEY(MP_AUTHOR) REFERENCES USER_INFO(USER_ID);   -- 매칭글(작성자아디)

ALTER TABLE MATCHING_POST_LIKE ADD CONSTRAINT MATCHING_POST_LIKE_FK FOREIGN KEY(MP_LIKE_SEQ) REFERENCES MATCHING_POST(MP_SEQ); -- 매칭글좋아요(매칭글SEQ)
ALTER TABLE MATCHING_POST_LIKE ADD CONSTRAINT MATCHING_POST_LIKE_FK2 FOREIGN KEY(MP_LIKE_USER) REFERENCES USER_INFO(USER_ID); -- 매칭글좋아요(아이디) 

ALTER TABLE CHAT_USER_INFO ADD CONSTRAINT CHAT_USER_INFO_FK1 FOREIGN KEY(CHATROOM_NO) REFERENCES CHAT; -- 채팅참여유저정보(채팅방번호)
ALTER TABLE CHAT_USER_INFO ADD CONSTRAINT CHAT_USER_INFO_FK2 FOREIGN KEY(CU_ID) REFERENCES USER_INFO(USER_ID); -- 채팅참여유저정보(참여유저아이디)

