-- 테이블 드랍
DROP TABLE POST; -- 게시글 TABLE DROP
DROP TABLE BOARD; -- 게시판 TABLE  DROP
DROP TABLE POST_THEMA; -- 말머리 TABLE DROP
DROP TABLE POST_LIKE; -- 게시물 좋아요 TABLE  DROP

-- 게시글
CREATE TABLE POST( 
    POST_SEQ NUMBER,
    POST_USER_ID VARCHAR2(50),
    POST_TITLE VARCHAR2(200) NOT NULL UNIQUE, -- 게시글 제목
    POST_CONTENT VARCHAR2(4000) NOT NULL, -- 게시글 내용
    POST_DATE DATE DEFAULT SYSDATE NOT NULL, -- 게시글 작성 시간
    POST_VIEW NUMBER NOT NULL, -- 조회수
    POST_ADDR VARCHAR2(200) NOT NULL UNIQUE, -- 게시글 주소
    POST_URL VARCHAR2(4000) NOT NULL, -- 게시글 사진,동영상 URL
    POST_NOTICE VARCHAR2(1000)DEFAULT 'N' CHECK(POST_NOTICE IN ('Y','N')), -- 공지사항(Y/N) 
    POST_THEMA_SEQ NUMBER,
    BOARD_SEQ NUMBER
);

CREATE TABLE BOARD( -- 일반 게시판
    BOARD_SEQ NUMBER,
    BOARD_NAME VARCHAR2(100) NOT NULL, -- 일반 게시판 이름
    BOARD_MANAGER CHAR(3)DEFAULT 'N' CHECK(BOARD_MANAGER IN ('Y','N')) -- 관리자 전용(Y/N)
);


CREATE TABLE POST_THEMA( -- 말머리  
    POST_THEMA_SEQ NUMBER,
    PT_NAME VARCHAR2(100) NOT NULL UNIQUE -- 말머리 제목
);

CREATE TABLE POST_LIKE(
    POST_LIKE_SEQ NUMBER,
    PL_DATE DATE DEFAULT SYSDATE NOT NULL,
    USER_ID VARCHAR2(50)-- 게시글 좋아요 누른 시간
    );
    
-- PK
ALTER TABLE POST ADD CONSTRAINT POST_NO_PK PRIMARY KEY(POST_SEQ); -- 게시글
ALTER TABLE BOARD ADD CONSTRAINT BOARD_NO_PK PRIMARY KEY(BOARD_SEQ); -- 게시판
ALTER TABLE POST_THEMA ADD CONSTRAINT POST_THEMA_NO_PK PRIMARY KEY(POST_THEMA_SEQ); -- 말머리
ALTER TABLE POST_LIKE ADD CONSTRAINT POST_LIKE_NO_PK PRIMARY KEY(POST_LIKE_SEQ); -- 게시글 좋아요

-- POST_LIKE_FK
ALTER TABLE POST_LIKE ADD CONSTRAINT POST_LIKE_FK FOREIGN KEY(POST_LIKE_SEQ) REFERENCES POST;
ALTER TABLE POST_LIKE ADD CONSTRAINT POST_USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO(USER_ID);

-- POST_FK
ALTER TABLE POST ADD CONSTRAINT POST_USER_ID_FK2 FOREIGN KEY(POST_USER_ID) REFERENCES USER_INFO(USER_ID);
ALTER TABLE POST ADD CONSTRAINT BOARD_BOARD_SEQ_FK FOREIGN KEY(BOARD_SEQ) REFERENCES BOARD(BOARD_SEQ);
ALTER TABLE POST ADD CONSTRAINT POST_THEMA_POST_THEMA_FK FOREIGN KEY(POST_THEMA_SEQ) REFERENCES POST_THEMA(POST_THEMA_SEQ); 

-- 시퀀스 드랍
DROP SEQUENCE SEQ_POST; -- 게시글 SEQUENCE DROP
DROP SEQUENCE SEQ_BOARD; -- 게시판 SEQUENCE DROP
DROP SEQUENCE SEQ_POST_THEMA; -- 말머리 SEQUENCE DROP
DROP SEQUENCE SEQ_POST_LIKE; -- 게시글 좋아요 SEQUENCE DROP

-- 시퀀스 생성
CREATE SEQUENCE SEQ_POST; -- 게시글 SEQUENCE
CREATE SEQUENCE SEQ_BOARD; -- 일반 게시판 SEQUENCE
CREATE SEQUENCE SEQ_POST_THEMA; -- 말머리 SEQUENCE
CREATE SEQUENCE SEQ_POST_LIKE; -- 게시글 좋아요 SEQUENCE


