-- 1
SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY "입학년도";

-- 2
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

-- 3
SELECT PROFESSOR_NAME "교수이름", (TO_CHAR(SYSDATE, 'YYYY') - (SUBSTR(PROFESSOR_SSN,1,2) + 1900)) - CASE WHEN TO_CHAR(SYSDATE, 'MMDD') <= SUBSTR(PROFESSOR_SSN,3,4) THEN 1 ELSE 0 END  "나이"
FROM TB_PROFESSOR
ORDER BY "나이";

-- 4
SELECT CASE WHEN LENGTH(PROFESSOR_NAME) = 1 THEN SUBSTR(PROFESSOR_NAME, 2, 1) WHEN LENGTH(PROFESSOR_NAME) = 4 THEN SUBSTR(PROFESSOR_NAME, 2, 3) ELSE SUBSTR(PROFESSOR_NAME, 2, 2) END  "이름"
FROM TB_PROFESSOR;

-- 5
SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(ENTRANCE_DATE), 'YYYY') - (TO_CHAR(SUBSTR(STUDENT_SSN, 1, 2))+1900) + 1 "입학시 나이"
FROM TB_STUDENT
WHERE TO_CHAR(TO_DATE(ENTRANCE_DATE), 'YYYY') - (TO_CHAR(SUBSTR(STUDENT_SSN, 1, 2))+1900) + 1 > 20
ORDER BY STUDENT_NAME;

-- 6
SELECT TO_CHAR(TO_DATE('20/12/25', 'YY/MM/DD'), 'DAY')
FROM DUAL;

-- 7
SELECT
TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'), 'YYYY/MM/DD') 값, 
TO_CHAR(TO_DATE('49/10/11', 'YY/DD/MM'), 'YYYY/MM/DD') 값, 
TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') 값, 
TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYY/MM/DD') 값
FROM DUAL;

-- 8 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO, 1, 1) != 'A'
ORDER BY STUDENT_NO;

-- 9
SELECT ROUND(AVG(POINT), 1) "평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A517178';

-- 10
SELECT DEPARTMENT_NO "학과번호", COUNT(STUDENT_NAME) "학생수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO;

-- 11
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12
SELECT SUBSTR(TERM_NO, 1, 4) "년도", ROUND(AVG(POINT), 1) "년도 별 평점"
FROM TB_GRADE
GROUP BY SUBSTR(TERM_NO, 1, 4), STUDENT_NO
HAVING STUDENT_NO = 'A112113'
ORDER BY SUBSTR(TERM_NO, 1, 4);

-- 13 휴학생수 0명인 학과가 안나와요 ㅠㅠ
SELECT DEPARTMENT_NO "학과코드명", COUNT(ABSENCE_YN) "휴학생 수"
FROM TB_STUDENT
GROUP BY DEPARTMENT_NO, ABSENCE_YN
HAVING ABSENCE_YN = 'Y'
ORDER BY DEPARTMENT_NO;

-- 14
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
ORDER BY STUDENT_NAME;

-- 15 왜 되는지 모르겠어요....
SELECT SUBSTR(TERM_NO,1,4) "년도", SUBSTR(TERM_NO,5,2) "학기", ROUND(AVG(POINT), 1)
FROM TB_GRADE
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),(SUBSTR(TERM_NO,5,2))), STUDENT_NO
HAVING STUDENT_NO = 'A112113'
ORDER BY "년도", "학기";


