SELECT STUDENT_NO "학번", STUDENT_NAME "이름", TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') "입학년도"
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY "입학년도";

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE LENGTH(PROFESSOR_NAME) != 3;

SELECT PROFESSOR_NAME "교수이름", (TO_CHAR(SYSDATE, 'YYYY') - (SUBSTR(PROFESSOR_SSN,1,2) + 1900)) + CASE WHEN TO_CHAR(SYSDATE, 'MMDD') <= SUBSTR(PROFESSOR_SSN,3,4) THEN 1 ELSE 0 END  "나이"
FROM TB_PROFESSOR
ORDER BY "나이";

SELECT CASE WHEN LENGTH(PROFESSOR_NAME) = 1 THEN SUBSTR(PROFESSOR_NAME, 2, 1) WHEN LENGTH(PROFESSOR_NAME) = 4 THEN SUBSTR(PROFESSOR_NAME, 2, 3) ELSE SUBSTR(PROFESSOR_NAME, 2, 2) END  "이름"
FROM TB_PROFESSOR;

SELECT STUDENT_NO, STUDENT_NAME, TO_CHAR(TO_DATE(ENTRANCE_DATE), 'YYYY') - (TO_CHAR(SUBSTR(STUDENT_SSN, 1, 2))+1900) + 1 "입학시 나이"
FROM TB_STUDENT
WHERE TO_CHAR(TO_DATE(ENTRANCE_DATE), 'YYYY') - (TO_CHAR(SUBSTR(STUDENT_SSN, 1, 2))+1900) + 1 > 19
ORDER BY STUDENT_NAME;
