 CREATE TABLE TB_CATEGORY (
    NAME VARCHAR2(10),
    USE_YN CHAR(1) DEFAULT 'Y'
);
CREATE TABLE TB_CLASS_TYPE(
    NO VARCHAR2(5) PRIMARY KEY,
    NAME VARCHAR2(10)
    );
--1
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM "순위"
FROM (
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
ORDER BY (SALARY + SALARY * NVL(BONUS, 0)) * 12 DESC
)
WHERE ROWNUM <= 5;

--2
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON (DEPT_CODE = DEPT_ID)
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) > (
SELECT SUM(SALARY) * 0.2
FROM EMPLOYEE
);

--3
WITH SAL AS (
SELECT SALARY
FROM EMPLOYEE)
SELECT SUM(SALARY), AVG(SALARY)
FROM SAL;
