CREATE TABLE USER_INFO(
    USER_ID VARCHAR2(50),
    USER_PWD VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_NICKNAME VARCHAR2(50) UNIQUE NOT NULL,
    USER_SUBSCRIPTION DATE DEFAULT SYSDATE NOT NULL,
    USER_ADDMIN CHAR DEFAULT 'N' NOT NULL CHECK(ADDMIN IN ('Y', 'N')),
    CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID),
    CONSTRAINT USER_NAME_FK FOREIGN KEY(USER_ID)
);
