DROP TABLE USER_INFO;
DROP TABLE USER_PROFILE;
DROP TABLE BLOCK_USERS;
DROP TABLE BAN_INFO;
DROP TABLE USER_LIKE;
DROP TABLE LIKE_INFO;

CREATE TABLE USER_INFO(
    USER_ID VARCHAR2(50),
    USER_PWD VARCHAR2(50) NOT NULL,
    USER_NAME VARCHAR2(30) NOT NULL,
    USER_NICKNAME VARCHAR2(50) UNIQUE NOT NULL,
    USER_SUBSCRIPTION DATE DEFAULT SYSDATE NOT NULL,
    USER_ADDMIN CHAR DEFAULT 'N' NOT NULL CHECK(USER_ADDMIN IN ('Y', 'N'))    
);

CREATE TABLE USER_PROFILE(
    USER_NAME VARCHAR2(50),
    AGE NUMBER,
    GENDER CHAR NOT NULL CHECK(GENDER IN ('남', '여')),
    PLACE VARCHAR2(300) NOT NULL,
    PHONE VARCHAR2(20) NOT NULL,
    PROFILE_IMG VARCHAR2(500),
    STATUS_MESSAGE VARCHAR2(1000),
    LOVER CHAR CHECK(LOVER IN ('Y', 'N')),
    BLOOD_TYPE VARCHAR2(5) CHECK(BLOOD_TYPE IN ('A', 'B', 'AB', 'O')),
    MBTI VARCHAR2(8),
    BIRTHDAY DATE
);

CREATE TABLE BLOCK_USERS(
    BLOCK_USER_SEQ NUMBER,
    USER_ID VARCHAR2(50) NOT NULL,
    BLOCK_ID VARCHAR2(50) NOT NULL,
    BLOCK_DATE DATE DEFAULT SYSDATE NOT NULL,
    BLOCK_REASON VARCHAR2(100),
    UNBLOCK CHAR DEFAULT 'N' NOT NULL CHECK(UNBLOCK IN ('Y', 'N'))
);

CREATE TABLE BAN_INFO(
    BAN_INFO_SEQ NUMBER,
    BAN_ID VARCHAR2(50) NOT NULL,
    BAN_START DATE DEFAULT SYSDATE NOT NULL,
    BAN_END DATE NOT NULL,
    BAN_REASON VARCHAR2(1000) NOT NULL
);

CREATE TABLE USER_LIKE(
    LIKE_UP_SEQ NUMBER,
    LIKE_UP_DATE DATE DEFAULT SYSDATE NOT NULL,
    LIKE_UP_USER VARCHAR(50) NOT NULL,
    LIKE_UP_TARGET_SEQ NUMBER
);

CREATE TABLE LIKE_INFO(
    LIKE_UP_TAGET_SEQ NUMBER,
    LIKE_UP_TAGET_USER VARCHAR(50) NOT NULL
);

ALTER TABLE USER_INFO ADD CONSTRAINT USER_ID_PK PRIMARY KEY(USER_ID);
ALTER TABLE USER_PROFILE ADD CONSTRAINT USER_PROFILE_PK PRIMARY KEY(USER_NAME);
ALTER TABLE BLOCK_USERS ADD CONSTRAINT BLOCK_USERS_PK PRIMARY KEY(BLOCK_USER_SEQ);
ALTER TABLE BAN_INFO ADD CONSTRAINT BAN_INFO_PK PRIMARY KEY(BAN_INFO_SEQ);
ALTER TABLE USER_LIKE ADD CONSTRAINT USER_LIKE_PK PRIMARY KEY(LIKE_UP_SEQ);
ALTER TABLE LIKE_INFO ADD CONSTRAINT LIKE_INFO_PK PRIMARY KEY(LIKE_UP_TAGET_SEQ);

ALTER TABLE USER_INFO ADD CONSTRAINT USER_NAME_FK FOREIGN KEY(USER_NAME) REFERENCES USER_PROFILE(USER_NAME);
ALTER TABLE BLOCK_USERS ADD CONSTRAINT USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USER_INFO (USER_ID);
ALTER TABLE BLOCK_USERS ADD CONSTRAINT USER_ID_FK2 FOREIGN KEY(BLOCK_ID) REFERENCES USER_INFO (USER_ID);
ALTER TABLE BAN_INFO ADD CONSTRAINT USER_ID_FK3 FOREIGN KEY(BAN_ID) REFERENCES USER_INFO(USER_ID);
ALTER TABLE USER_LIKE ADD CONSTRAINT USER_ID_FK4 FOREIGN KEY(LIKE_UP_USER) REFERENCES USER_INFO(USER_ID);
ALTER TABLE LIKE_INFO ADD CONSTRAINT USER_ID_FK5 FOREIGN KEY(LIKE_UP_TAGET_USER) REFERENCES USER_INFO(USER_ID);

CREATE SEQUENCE SEQ_BLOCK_USERS;
CREATE SEQUENCE SEQ_BAN_INFO;
CREATE SEQUENCE SEQ_USER_LIKE; 
CREATE SEQUENCE SEQ_LIKE_INFO;
